config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # If you have a dedicated config/environments/staging.rb
  mount LetterOpenerWeb::Engine, at: "/mail"

  # Defines the root path route ("/")
  root "root#index"
  post "/", to: "root#create"
  post '/send_email', to: 'email_sender#send_email'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_sender_controller.rb
class EmailSenderController < ApplicationController
    def send_email
        recipient_email = 'recipient@example.com' # Replace with the actual recipient's email address
    
        # Create and deliver the email using Action Mailer
        UserMailer.send_email(recipient_email).deliver_now
    
        # Optionally, you can redirect to a success page or display a flash message
        redirect_to root_path, notice: 'Email sent successfully!'
      end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_sender_helper.rb
module EmailSenderHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/email_sender/send_email.html.erb
<div class="container">
  <h1>Send Email</h1>
  <%= button_to 'Send Email', send_email_path, method: :post, class: 'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupportEng</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<%= form_tag send_email_path, class: "send-email" do %>
  <%= submit_tag "Click to Send Email", style: "margin: 10px; padding: 10px" %>
<% end %>

<script>
document.querySelector(".send-email").onsubmit = function(e) {
  e.preventDefault()

  fetch(e.target.action, {
    method: "POST",
    headers: {
      "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').content
    }
  }).then(function(response) {
    if (response.ok) {
      window.open('/mail', '_blank')
    } else {
      console.error(response)
    }
  });
}
</script>